-- H2-compatible test schema (translated from V1__init.sql)
-- UUIDs are generated by Hibernate (@GeneratedValue) or supplied explicitly in data.sql.
-- Triggers and plpgsql functions are omitted; extensions not supported in H2.

CREATE TABLE IF NOT EXISTS users (
    id                     UUID         NOT NULL PRIMARY KEY,
    email                  VARCHAR(255) NOT NULL UNIQUE,
    password_hash          VARCHAR(255) NOT NULL,
    role                   VARCHAR(32)  NOT NULL,
    full_name              VARCHAR(255) NOT NULL,
    is_active              BOOLEAN      NOT NULL DEFAULT TRUE,
    phone                  VARCHAR(32),
    preferred_language     VARCHAR(8),
    must_change_password   BOOLEAN      NOT NULL DEFAULT FALSE,
    last_login_at          TIMESTAMP WITH TIME ZONE,
    failed_login_attempts  INTEGER      NOT NULL DEFAULT 0,
    locked_until           TIMESTAMP WITH TIME ZONE,
    consent_given_at       TIMESTAMP WITH TIME ZONE,
    gmt_create             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    gmt_modified           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS patients (
    id                       UUID         NOT NULL PRIMARY KEY,
    user_id                  UUID         REFERENCES users(id),
    national_id_ciphertext   VARBINARY,
    national_id_fingerprint  VARCHAR(64)  UNIQUE,
    full_name                VARCHAR(255) NOT NULL,
    date_of_birth            DATE,
    gender                   VARCHAR(16),
    phone                    VARCHAR(32),
    email                    VARCHAR(255),
    preferred_language       VARCHAR(8),
    registration_source      VARCHAR(16) NOT NULL DEFAULT 'STAFF_LED',
    consent_given_at         TIMESTAMP WITH TIME ZONE,
    consent_version          VARCHAR(16),
    gmt_create               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    gmt_modified             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS doctors (
    id                       UUID         NOT NULL PRIMARY KEY,
    user_id                  UUID         NOT NULL UNIQUE REFERENCES users(id),
    mmc_number               VARCHAR(32)  NOT NULL UNIQUE,
    specialty                VARCHAR(64)  NOT NULL,
    signature_image_url      VARCHAR(512),
    is_accepting_patients    BOOLEAN      NOT NULL DEFAULT TRUE,
    gmt_create               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    gmt_modified             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS staff_profiles (
    id           UUID         NOT NULL PRIMARY KEY,
    user_id      UUID         NOT NULL UNIQUE REFERENCES users(id),
    employee_id  VARCHAR(32)  UNIQUE,
    notes        VARCHAR(255),
    gmt_create   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    gmt_modified TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS patient_clinical_profiles (
    id                              UUID NOT NULL PRIMARY KEY,
    patient_id                      UUID NOT NULL UNIQUE REFERENCES patients(id) ON DELETE CASCADE,
    weight_kg                       DECIMAL(5,2),
    weight_kg_updated_at            TIMESTAMP WITH TIME ZONE,
    weight_kg_source                VARCHAR(32),
    height_cm                       DECIMAL(5,2),
    height_cm_updated_at            TIMESTAMP WITH TIME ZONE,
    height_cm_source                VARCHAR(32),
    drug_allergies                  CLOB NOT NULL DEFAULT '[]',
    drug_allergies_updated_at       TIMESTAMP WITH TIME ZONE,
    drug_allergies_source           VARCHAR(32),
    chronic_conditions              CLOB NOT NULL DEFAULT '[]',
    chronic_conditions_updated_at   TIMESTAMP WITH TIME ZONE,
    chronic_conditions_source       VARCHAR(32),
    regular_medications             CLOB NOT NULL DEFAULT '[]',
    regular_medications_updated_at  TIMESTAMP WITH TIME ZONE,
    regular_medications_source      VARCHAR(32),
    pregnancy_status                VARCHAR(32),
    pregnancy_edd                   DATE,
    pregnancy_updated_at            TIMESTAMP WITH TIME ZONE,
    pregnancy_source                VARCHAR(32),
    completeness_state              VARCHAR(16) NOT NULL DEFAULT 'INCOMPLETE',
    gmt_create                      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    gmt_modified                    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS neo4j_projection_outbox (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id    UUID         NOT NULL,
    operation       VARCHAR(64)  NOT NULL,
    payload         CLOB         NOT NULL,
    status          VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    attempts        INTEGER      NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    last_error      CLOB,
    enqueued_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    completed_at    TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS visits (
    id            UUID         NOT NULL PRIMARY KEY,
    patient_id    UUID         NOT NULL REFERENCES patients(id),
    doctor_id     UUID         NOT NULL REFERENCES users(id),
    status        VARCHAR(32)  NOT NULL DEFAULT 'SCHEDULED',
    started_at    TIMESTAMP WITH TIME ZONE,
    finalized_at  TIMESTAMP WITH TIME ZONE,
    report_draft  CLOB,
    gmt_create    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    gmt_modified  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS pre_visit_reports (
    id           UUID         NOT NULL PRIMARY KEY,
    visit_id     UUID         NOT NULL UNIQUE REFERENCES visits(id),
    structured   CLOB         NOT NULL DEFAULT '{}',
    source       VARCHAR(32)  NOT NULL DEFAULT 'AI',
    gmt_create   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    gmt_modified TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS medical_reports (
    id                  UUID         NOT NULL PRIMARY KEY,
    visit_id            UUID         NOT NULL UNIQUE REFERENCES visits(id),
    subjective          CLOB         NOT NULL DEFAULT '',
    objective           CLOB         NOT NULL DEFAULT '',
    assessment          CLOB         NOT NULL DEFAULT '',
    plan                CLOB         NOT NULL DEFAULT '',
    ai_draft_hash       VARCHAR(64),
    is_finalized        BOOLEAN      NOT NULL DEFAULT FALSE,
    finalized_by        UUID         REFERENCES users(id),
    finalized_at        TIMESTAMP WITH TIME ZONE,
    preview_approved_at TIMESTAMP WITH TIME ZONE,
    summary_en          CLOB,
    summary_ms          CLOB,
    gmt_create          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    gmt_modified        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS post_visit_summaries (
    id              UUID         NOT NULL PRIMARY KEY,
    visit_id        UUID         NOT NULL UNIQUE REFERENCES visits(id),
    patient_summary CLOB         NOT NULL DEFAULT '',
    gmt_create      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    gmt_modified    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS medications (
    id             UUID         NOT NULL PRIMARY KEY,
    visit_id       UUID         NOT NULL REFERENCES visits(id),
    name           VARCHAR(255) NOT NULL,
    dosage         VARCHAR(128) NOT NULL,
    frequency      VARCHAR(128) NOT NULL,
    duration_days  INTEGER,
    instructions   CLOB,
    gmt_create     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    gmt_modified   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS audit_log (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    actor_user_id  UUID         REFERENCES users(id),
    actor_role     VARCHAR(32),
    action         VARCHAR(16)  NOT NULL,
    resource_type  VARCHAR(64)  NOT NULL,
    resource_id    VARCHAR(128),
    correlation_id VARCHAR(64),
    payload_hash   VARCHAR(64),
    ip_address     VARCHAR(64),
    metadata       CLOB         NOT NULL DEFAULT '{}'
);
