-- H2-compatible test schema (translated from V1__init.sql)
-- UUIDs are generated by Hibernate (@GeneratedValue) or supplied explicitly in data.sql.
-- Triggers and plpgsql functions are omitted; extensions not supported in H2.

CREATE TABLE IF NOT EXISTS users (
    id                     UUID         NOT NULL PRIMARY KEY,
    email                  VARCHAR(255) NOT NULL UNIQUE,
    password_hash          VARCHAR(255) NOT NULL,
    role                   VARCHAR(32)  NOT NULL,
    full_name              VARCHAR(255) NOT NULL,
    is_active              BOOLEAN      NOT NULL DEFAULT TRUE,
    phone                  VARCHAR(32),
    preferred_language     VARCHAR(8),
    must_change_password   BOOLEAN      NOT NULL DEFAULT FALSE,
    last_login_at          TIMESTAMP WITH TIME ZONE,
    failed_login_attempts  INTEGER      NOT NULL DEFAULT 0,
    locked_until           TIMESTAMP WITH TIME ZONE,
    consent_given_at       TIMESTAMP WITH TIME ZONE,
    gmt_create             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    gmt_modified           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS patients (
    id                       UUID         NOT NULL PRIMARY KEY,
    user_id                  UUID         REFERENCES users(id),
    national_id_ciphertext   VARBINARY,
    national_id_fingerprint  VARCHAR(64)  UNIQUE,
    full_name                VARCHAR(255) NOT NULL,
    date_of_birth            DATE,
    gender                   VARCHAR(16),
    phone                    VARCHAR(32),
    email                    VARCHAR(255),
    preferred_language       VARCHAR(8),
    registration_source      VARCHAR(16) NOT NULL DEFAULT 'STAFF_LED',
    consent_given_at         TIMESTAMP WITH TIME ZONE,
    consent_version          VARCHAR(16),
    gmt_create               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    gmt_modified             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS doctors (
    id                       UUID         NOT NULL PRIMARY KEY,
    user_id                  UUID         NOT NULL UNIQUE REFERENCES users(id),
    mmc_number               VARCHAR(32)  NOT NULL UNIQUE,
    specialty                VARCHAR(64)  NOT NULL,
    signature_image_url      VARCHAR(512),
    is_accepting_patients    BOOLEAN      NOT NULL DEFAULT TRUE,
    gmt_create               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    gmt_modified             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS staff_profiles (
    id           UUID         NOT NULL PRIMARY KEY,
    user_id      UUID         NOT NULL UNIQUE REFERENCES users(id),
    employee_id  VARCHAR(32)  UNIQUE,
    notes        VARCHAR(255),
    gmt_create   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    gmt_modified TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS patient_clinical_profiles (
    id                              UUID NOT NULL PRIMARY KEY,
    patient_id                      UUID NOT NULL UNIQUE REFERENCES patients(id) ON DELETE CASCADE,
    weight_kg                       DECIMAL(5,2),
    weight_kg_updated_at            TIMESTAMP WITH TIME ZONE,
    weight_kg_source                VARCHAR(32),
    height_cm                       DECIMAL(5,2),
    height_cm_updated_at            TIMESTAMP WITH TIME ZONE,
    height_cm_source                VARCHAR(32),
    drug_allergies                  CLOB NOT NULL DEFAULT '[]',
    drug_allergies_updated_at       TIMESTAMP WITH TIME ZONE,
    drug_allergies_source           VARCHAR(32),
    chronic_conditions              CLOB NOT NULL DEFAULT '[]',
    chronic_conditions_updated_at   TIMESTAMP WITH TIME ZONE,
    chronic_conditions_source       VARCHAR(32),
    regular_medications             CLOB NOT NULL DEFAULT '[]',
    regular_medications_updated_at  TIMESTAMP WITH TIME ZONE,
    regular_medications_source      VARCHAR(32),
    pregnancy_status                VARCHAR(32),
    pregnancy_edd                   DATE,
    pregnancy_updated_at            TIMESTAMP WITH TIME ZONE,
    pregnancy_source                VARCHAR(32),
    completeness_state              VARCHAR(16) NOT NULL DEFAULT 'INCOMPLETE',
    gmt_create                      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    gmt_modified                    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS neo4j_projection_outbox (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id    UUID         NOT NULL,
    operation       VARCHAR(64)  NOT NULL,
    payload         CLOB         NOT NULL,
    status          VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    attempts        INTEGER      NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    last_error      CLOB,
    enqueued_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    completed_at    TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS visits (
    id               UUID         NOT NULL PRIMARY KEY,
    patient_id       UUID         NOT NULL REFERENCES patients(id),
    doctor_id        UUID         NOT NULL REFERENCES users(id),
    status           VARCHAR(32)  NOT NULL DEFAULT 'SCHEDULED',
    started_at       TIMESTAMP WITH TIME ZONE,
    finalized_at     TIMESTAMP WITH TIME ZONE,
    report_draft     CLOB,
    reference_number VARCHAR(32)  UNIQUE,
    gmt_create       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    gmt_modified     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- V14: Per-day visit reference number counter.
-- ReferenceNumberDomainService uses a portable UPDATE-then-INSERT-on-miss
-- upsert (no ON CONFLICT), which works on both Postgres and H2.
CREATE TABLE IF NOT EXISTS visit_reference_counter (
    counter_date DATE    NOT NULL PRIMARY KEY,
    last_seq     INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS pre_visit_reports (
    id           UUID         NOT NULL PRIMARY KEY,
    visit_id     UUID         NOT NULL UNIQUE REFERENCES visits(id),
    structured   CLOB         NOT NULL DEFAULT '{}',
    source       VARCHAR(32)  NOT NULL DEFAULT 'AI',
    gmt_create   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    gmt_modified TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS medical_reports (
    id                  UUID         NOT NULL PRIMARY KEY,
    visit_id            UUID         NOT NULL UNIQUE REFERENCES visits(id),
    subjective          CLOB         NOT NULL DEFAULT '',
    objective           CLOB         NOT NULL DEFAULT '',
    assessment          CLOB         NOT NULL DEFAULT '',
    plan                CLOB         NOT NULL DEFAULT '',
    ai_draft_hash       VARCHAR(64),
    is_finalized        BOOLEAN      NOT NULL DEFAULT FALSE,
    finalized_by        UUID         REFERENCES users(id),
    finalized_at        TIMESTAMP WITH TIME ZONE,
    preview_approved_at TIMESTAMP WITH TIME ZONE,
    summary_en          CLOB,
    summary_ms          CLOB,
    gmt_create          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    gmt_modified        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS post_visit_summaries (
    id              UUID         NOT NULL PRIMARY KEY,
    visit_id        UUID         NOT NULL UNIQUE REFERENCES visits(id),
    patient_summary CLOB         NOT NULL DEFAULT '',
    gmt_create      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    gmt_modified    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS medications (
    id             UUID         NOT NULL PRIMARY KEY,
    visit_id       UUID         NOT NULL REFERENCES visits(id),
    name           VARCHAR(255) NOT NULL,
    dosage         VARCHAR(128) NOT NULL,
    frequency      VARCHAR(128) NOT NULL,
    duration_days  INTEGER,
    instructions   CLOB,
    gmt_create     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    gmt_modified   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS audit_log (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    actor_user_id  UUID         REFERENCES users(id),
    actor_role     VARCHAR(32),
    action         VARCHAR(16)  NOT NULL
                   CHECK (action IN ('READ','CREATE','UPDATE','DELETE','LOGIN','EXPORT')),
    resource_type  VARCHAR(64)  NOT NULL,
    resource_id    VARCHAR(128),
    correlation_id VARCHAR(64),
    payload_hash   VARCHAR(64),
    ip_address     VARCHAR(64),
    metadata       CLOB         NOT NULL DEFAULT '{}'
);

-- Evaluator findings — H2 mirror of the Postgres evaluator_findings table.
-- jsonb→CLOB; the partial-uniqueness/PDPA append-only triggers are
-- production-only (omitted here).
CREATE TABLE IF NOT EXISTS evaluator_findings (
    id                      UUID                     NOT NULL PRIMARY KEY,
    visit_id                UUID                     NOT NULL REFERENCES visits(id),
    category                VARCHAR(32)              NOT NULL,
    severity                VARCHAR(16)              NOT NULL,
    field_path              VARCHAR(255),
    message                 CLOB                     NOT NULL,
    details                 CLOB                     NOT NULL DEFAULT '{}',
    acknowledged_at         TIMESTAMP WITH TIME ZONE,
    acknowledged_by         UUID,
    acknowledgement_reason  VARCHAR(255),
    superseded_at           TIMESTAMP WITH TIME ZONE,
    gmt_create              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    gmt_modified            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- =====================================================================
-- V11: Schedule + Appointment tables (H2-translated)
--
-- Differences from V11__schedule_and_notifications.sql (Postgres):
--   1. jsonb -> CLOB  (Hibernate @JdbcTypeCode(SqlTypes.JSON) handles both)
--   2. Partial unique indexes (WHERE …) omitted — H2 does not support
--      predicate-based partial uniques. Production Postgres enforces
--      uq_appointments_active_slot and uq_appointments_active_visit.
--   3. Triggers / plpgsql omitted (not supported in H2).
--   4. ALTER TABLE patients … ADD COLUMN omitted — columns already
--      present in the base table definition above if needed, or added here.
-- =====================================================================

ALTER TABLE patients
    ADD COLUMN IF NOT EXISTS whatsapp_consent_at      TIMESTAMP WITH TIME ZONE NULL;
ALTER TABLE patients
    ADD COLUMN IF NOT EXISTS whatsapp_consent_version VARCHAR(16) NULL;

CREATE TABLE IF NOT EXISTS schedule_template (
    id                       UUID         NOT NULL PRIMARY KEY,
    doctor_id                UUID         NOT NULL REFERENCES doctors(id),
    effective_from           DATE         NOT NULL,
    slot_minutes             SMALLINT     NOT NULL CHECK (slot_minutes IN (10,15,20,30)),
    weekly_hours             CLOB         NOT NULL,
    cancel_lead_hours        SMALLINT     NOT NULL DEFAULT 2,
    generation_horizon_days  SMALLINT     NOT NULL DEFAULT 28,
    gmt_create               TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    gmt_modified             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_schedule_template_doctor_eff UNIQUE (doctor_id, effective_from)
);

CREATE TABLE IF NOT EXISTS appointment_slots (
    id           UUID         NOT NULL PRIMARY KEY,
    doctor_id    UUID         NOT NULL REFERENCES doctors(id),
    start_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    end_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    status       VARCHAR(16)  NOT NULL
                  CHECK (status IN ('AVAILABLE','BOOKED','BLOCKED','CLOSED')),
    gmt_create   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    gmt_modified TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT slot_window_valid CHECK (end_at > start_at),
    CONSTRAINT uq_slots_doctor_start UNIQUE (doctor_id, start_at)
    -- NOTE: Partial unique index (WHERE status='AVAILABLE') from Postgres V11
    -- is omitted here — H2 does not support predicate partial uniques.
);

CREATE TABLE IF NOT EXISTS appointments (
    id               UUID         NOT NULL PRIMARY KEY,
    slot_id          UUID         NOT NULL REFERENCES appointment_slots(id),
    patient_id       UUID         NOT NULL REFERENCES patients(id),
    visit_id         UUID         NOT NULL REFERENCES visits(id),
    appointment_type VARCHAR(16)  NOT NULL
                      CHECK (appointment_type IN ('NEW_SYMPTOM','FOLLOW_UP')),
    parent_visit_id  UUID         NULL REFERENCES visits(id),
    status           VARCHAR(16)  NOT NULL
                      CHECK (status IN ('BOOKED','CHECKED_IN','CANCELLED','COMPLETED','NO_SHOW')),
    cancel_reason    VARCHAR(64)  NULL,
    cancelled_at     TIMESTAMP WITH TIME ZONE NULL,
    cancelled_by     UUID         NULL REFERENCES users(id),
    checked_in_at    TIMESTAMP WITH TIME ZONE NULL,
    gmt_create       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    gmt_modified     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
    -- NOTE: Partial unique indexes uq_appointments_active_slot and
    -- uq_appointments_active_visit (WHERE status='BOOKED') from Postgres V11
    -- are omitted — H2 does not support predicate partial uniques.
    -- Production Postgres enforces one active booking per slot/visit.
);

CREATE TABLE IF NOT EXISTS schedule_day_overrides (
    id            UUID         NOT NULL PRIMARY KEY,
    doctor_id     UUID         NOT NULL REFERENCES doctors(id),
    override_date DATE         NOT NULL,
    override_type VARCHAR(16)  NOT NULL
                   CHECK (override_type IN ('DAY_CLOSED','WINDOW_BLOCKED')),
    window_start  TIME         NULL,
    window_end    TIME         NULL,
    reason        VARCHAR(255) NULL,
    created_by    UUID         NOT NULL REFERENCES users(id),
    gmt_create    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT window_required_when_blocked
        CHECK (override_type <> 'WINDOW_BLOCKED'
               OR (window_start IS NOT NULL AND window_end IS NOT NULL
                   AND window_end > window_start))
);

-- =====================================================================
-- V11 (continued): Notification tables (H2-translated)
--
-- Differences from V11__schedule_and_notifications.sql (Postgres):
--   1. jsonb -> CLOB  (Hibernate @JdbcTypeCode(SqlTypes.JSON) handles both)
--   2. Partial unique index (WHERE status IN …) on notification_outbox omitted
--      — H2 does not support predicate partial uniques.
--   3. Triggers omitted (not supported in H2).
-- =====================================================================

CREATE TABLE IF NOT EXISTS notification_outbox (
    id                   UUID         NOT NULL PRIMARY KEY,
    event_type           VARCHAR(48)  NOT NULL,
    channel              VARCHAR(16)  NOT NULL
                          CHECK (channel IN ('WHATSAPP')),
    template_id          VARCHAR(64)  NOT NULL,
    recipient_patient_id UUID         NOT NULL REFERENCES patients(id),
    payload              CLOB         NOT NULL,
    idempotency_key      VARCHAR(128) NOT NULL,
    status               VARCHAR(24)  NOT NULL
                          CHECK (status IN
                            ('PENDING','SENDING','SENT','FAILED','SKIPPED_NO_CONSENT')),
    attempts             SMALLINT     NOT NULL DEFAULT 0,
    next_attempt_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    last_error           CLOB         NULL,
    sent_at              TIMESTAMP WITH TIME ZONE NULL,
    gmt_create           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    gmt_modified         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_outbox_idempotency UNIQUE (idempotency_key)
);

CREATE TABLE IF NOT EXISTS whatsapp_message_log (
    id                UUID         NOT NULL PRIMARY KEY,
    outbox_id         UUID         NOT NULL REFERENCES notification_outbox(id),
    twilio_sid        VARCHAR(64)  NULL,
    to_phone_hash     VARCHAR(64)  NOT NULL,
    template_id       VARCHAR(64)  NOT NULL,
    rendered_locale   VARCHAR(8)   NOT NULL,
    delivery_status   VARCHAR(24)  NOT NULL
                       CHECK (delivery_status IN
                         ('QUEUED','SENT','DELIVERED','READ','FAILED','UNDELIVERED')),
    twilio_error_code VARCHAR(16)  NULL,
    gmt_create        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    gmt_modified      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
