-- V5__agent_turns.sql — append-only agent session log.
-- Referenced from docs/superpowers/specs/2026-04-22-subproject-a-agent-rebuild-design.md §3.
-- Flyway NOT used (per CLAUDE.md). Apply via Supabase SQL editor.

CREATE TABLE agent_turns (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id          UUID        NOT NULL REFERENCES visits(id) ON DELETE CASCADE,
    agent_type        VARCHAR(32) NOT NULL
        CHECK (agent_type IN ('pre_visit', 'report')),
    turn_index        INTEGER     NOT NULL,
    role              VARCHAR(16) NOT NULL
        CHECK (role IN ('system', 'user', 'assistant', 'tool')),
    content           TEXT        NOT NULL,
    reasoning         TEXT,
    tool_call_name    VARCHAR(64),
    tool_call_args    JSONB,
    tool_result       JSONB,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (visit_id, agent_type, turn_index)
);

CREATE INDEX idx_agent_turns_visit_agent
    ON agent_turns(visit_id, agent_type, turn_index);

CREATE OR REPLACE FUNCTION agent_turns_block_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'agent_turns is append-only';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER agent_turns_no_update
    BEFORE UPDATE ON agent_turns
    FOR EACH ROW EXECUTE FUNCTION agent_turns_block_mutation();

CREATE TRIGGER agent_turns_no_delete
    BEFORE DELETE ON agent_turns
    FOR EACH ROW EXECUTE FUNCTION agent_turns_block_mutation();
